### ISSUE TITLE
Crash on 1.18.2 Startup Fabric

### ISSUE THREAD

**Issue by GhostGekko** [Enchanted-Games/vertical-slabs#12]
When loading MC Fabric 1.18.2 using fabric-loader-0.14.11-1.18.2, the game crashes with error:
"The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'enchanted-vertical-slabs'!"

[crash-2022-12-16_20.27.18-client.txt](https://github.com/Enchanted-Games/vertical-slabs/files/10250888/crash-2022-12-16_20.27.18-client.txt)

**Comment by Enchanted-Games** [comment]
Tested using the latest version of Fabric Loader (0.14.11) and Fabric API (0.67.0) for 1.18.2 and the game loaded fine. Try either updating fabric api or removing other mods that may be conflicting. 
If the crash still persists, would you mind sending the full game log (.minecraft/logs/latest.log)

**Comment by GhostGekko** [comment]
Just tested it again making sure to have the same installed configuration you mentioned (Fabric Loader (1.14.11) and Fabric API (0.67.0-1.18.2) and it has the same issue. No other mods are installed. Here is the latest full game log:

[latest.log](https://github.com/Enchanted-Games/vertical-slabs/files/10252963/latest.log)

**Comment by GhostGekko** [comment]
Version 1.4.1 appears to load just fine. It appears that 1.5.1 does not want to load.

**Comment by GhostGekko** [comment]
I feel a little dumb for this, but looking into the files it appears that 1.5.1 is built for 1.19; however it is listed on curse forge as being for 1.18.

**Comment by Enchanted-Games** [comment]
There was an issue in 1.5.1 that made it not load in 1.18 but it was fixed in 1.6

**Comment by Enchanted-Games** [comment]
Turns out I forgot to upload 1.6 to curseforge, I’ll do that now and also remove the 1.18 tag from version 1.5.1
