### ISSUE TITLE
Unable to mine blocks that require pickaxes

### ISSUE THREAD

**Issue by t1an-xyz** [Enchanted-Games/vertical-slabs#13]
**Describe the bug**
When mining a block such as stone with a pickaxe, it acts as if I am mining it without a pickaxe.  It mines really slowly and does not drop any item.  I have no other mods installed other than fabric api.

**To Reproduce**
1. Create a new survival world
2. Get any pickaxe
3. Mine a stone block

**Expected behavior**
The block should mine quickly and drop an item like in vanilla Minecraft.

**Environment**
 - Mod Version: 1.6
 - Fabric Version: 0.14.12-1.18.2
 - Fabric API Version: 0.67.0

**Comment by SparklesTR** [comment]
Yes, thats exactly what happens for me

**Comment by Enchanted-Games** [comment]
Released fix on github, will publish it on other download sites
https://github.com/Enchanted-Games/vertical-slabs/releases/tag/v1.6
