### ISSUE TITLE
Modrinth versions are merged

### ISSUE THREAD

**Issue by RandomGgames** [Enchanted-Games/vertical-slabs#15]
https://modrinth.com/mod/enchanted-vertical-slabs/version/1.6

There are two files uploaded into version 1.6. One compatible only with 1.18 and the other only computable with 1.19. They should be separated into two separate versions on Modrinth, each with only one file. Their API cannot differentiate which mod is for what version with the way you have uploaded it, thus causing wrong files to be downloaded for automatic mod updaters/downloaders since the 1.18 file is technically grouped with the 1.19.2 file and it is the primary.

**Comment by Enchanted-Games** [comment]
Fixed, I didn’t know this so thanks for letting me know
