### ISSUE TITLE
New versions won't load?

### ISSUE THREAD

**Issue by muhammedesadcomert** [Enchanted-Games/vertical-slabs#17]
Why don't you upload the 1.7.1 version to the mod's Curseforge/Modrinth page? I'm saying **new**, but it was released on **March 18**.

![Curseforge](https://user-images.githubusercontent.com/46245749/236683934-1b915b2f-09a7-4cb8-9a3a-402cbf82d2dc.png)

![Modrinth](https://user-images.githubusercontent.com/46245749/236683942-d762ba67-f48a-4d44-a2b1-b4077e556a19.png)

**Comment by Enchanted-Games** [comment]
it's unfinished and was meant tto be a pre-release on here

**Comment by muhammedesadcomert** [comment]
Ok, then I am closing the issue
