### ISSUE TITLE
[1.19.2 / All] Vertical slabs don't connect to glass panes

### ISSUE THREAD

**Issue by twenty41** [Enchanted-Games/vertical-slabs#18]
**Bug description**
(This is sort of more of a suggestion but I think it is the block behavior that anyone would expect, and it doesn't happen)
When placing a glass pane in the middle of vertical slabs, the pane does not connect

**To Reproduce**
1. Place two vertical slabs with a pane in-between
2. View

**Expected behavior**
I would expect the glass pane to be flat and connect to the blocks around it (Maybe I'm wrong but I think most people would expect this)

**Environment**
 - Mod Version: MC-1.19-enchanted-vertical-slabs-1.6.2.jar
 - Fabric Version: Fabric 0.14.19
 - Fabric API Version: fabric-api-0.76.0+1.19.2

**Additional content**
What happens:
![image](https://github.com/Enchanted-Games/vertical-slabs/assets/46447750/c9023ba5-d5b4-4c94-b59f-913497db1627)
What I think should happen, but with slabs:
![image](https://github.com/Enchanted-Games/vertical-slabs/assets/46447750/26baae1c-960b-4d33-94e7-9bc8a91cdfbd)

Also happens with iron bars

**Comment by Enchanted-Games** [comment]
That’s actually a great suggestion, thanks! I’ll see if I can get this to work, hopefully before 1.20 releases

**Comment by Enchanted-Games** [comment]
added in v1.8
