### ISSUE TITLE
Incompatibility with MoreCulling

### ISSUE THREAD

**Issue by nightpool** [Enchanted-Games/vertical-slabs#22]
**Describe the bug**
When trying to place a vertical slab from creative mode, the game crashes

**To Reproduce**
1. Install SimplyOptimized
2. Install enchanted vertical slabs
3. create a new creative world
4. give yourself a slab from the creative menu
5. place the slab in the world

**Expected behavior**
The slab renders in the world

**Actual behavior**
The game crashes

**Environment**
 - Mod Version: 1.9.1
 - Minecraft version: 1.20.1
 - Fabric Version: 0.14.24
 - Fabric API Version: 0.90.7

**Additional content**
https://mclo.gs/Ki67wg8

**Comment by Enchanted-Games** [comment]
Will look into it and try and fix it for the 1.20.3 release

**Comment by Enchanted-Games** [comment]
Should be fixed as of v1.9.3
