### ISSUE TITLE
78 lines of errors in log on fabric 1.20.6

### ISSUE THREAD

**Issue by nickademas** [Enchanted-Games/vertical-slabs#32]
**Describe the bug**
the mod is working properly but it just annoys me

**To Reproduce**
Join a world

**Environment**
 - Mod Version: 1.10.1
 - Mod Loader: 0.15.11
 - Fabric API Version: 0.99.0

**Additional content**

[latest.log](https://github.com/Enchanted-Games/vertical-slabs/files/15491485/latest.log)

**Comment by Enchanted-Games** [comment]
Fixed in v1.10.2
