### ISSUE TITLE
[Bug] AI Attempts to Walk Through Vertical Slabs

### ISSUE THREAD

**Issue by CYNO-MC** [Enchanted-Games/vertical-slabs#5]
**Describe the bug**
When using Vertical Slabs, typically around a doorway, Villagers appear to mentally shut down. They will just run into the wall and continue jumping if vertical slabs surrounds the door. I believe there is a missing attribute for AI blocking, though I'm gravely unfamiliar with the terminology. 

**Steps to reproduce the behavior:**
1. Build an Enclosed Structure with a Vertical Slab Doorway;
Vertical Slab = X  Door = O

XXX
XOX
XOX

2. Place a bed inside of the Enclosed Structure & have a Villager assume it

3.  Observe the Villager break down mentally; He will struggle to walk through the doorway over time. 

**Expected behavior**
AI Blocking Attribute assigned to the Vertical Slabs; To have the AI pass through normally.

**Environment**
 - Mod Version: 1.4.1-1.18.2
 - Fabric Version: 0.13.3
 - Fabric API Version: 0.48.0

**Additional context**
This is occurring within a unfinished modpack; The only Villagers mods installed are:
Villager Names
Villager Death Messages
& MoreVillagers

**Comment by Enchanted-Games** [comment]
This seems more like an issue with minecrafts AI itself and it not understanding the odd shape of the vertical slabs. This same thing happens with trapdoors but its just not as noticeable because theyre thinner
