### ISSUE TITLE
Vertical Slabs adds its mod icon to the block atlas

### ISSUE THREAD

**Issue by gliscowo** [Enchanted-Games/vertical-slabs#6]
**Describe the bug**
In order to have a texture for the [`vertical_slabs_icon`](https://github.com/Enchanted-Games/vertical-slabs/blob/f7c6ef47549840892dbaf8b387d7dc84986f310a/src/main/java/games/enchanted/registry/ModItems.java#L70) item, the mod icon is [declared as a texture in that item's model](https://github.com/Enchanted-Games/vertical-slabs/blob/f7c6ef47549840892dbaf8b387d7dc84986f310a/src/main/resources/assets/enchanted-vertical-slabs/models/item/vertical_slabs_icon.json#L4). This causes it to be stitched in to the block atlas, majorly inflating the size of that texture

**Expected behavior**
The 285kb, 1024x1024 icon texture is not used for an item and stitched into the block atlas

**Environment**
 - Mod Version: 1.5
 - Fabric Version: 0.14.10
 - Fabric API Version: 0.64.0+1.19.2

**Additional content**
Feast your eyes upon this block atlas, pulled from a medium sized modpack
![block](https://user-images.githubusercontent.com/15788224/198841086-70c09960-e0d3-4854-9aa0-7382bea80e77.png)

**Comment by Enchanted-Games** [comment]
Fixed in 1.5.1

Also reduced the size of the regular icon texture to 256x
