### ISSUE TITLE
[Fabric 1.18.2] Initializing game problem

### ISSUE THREAD

**Issue by Ryuushen** [Enchanted-Games/vertical-slabs#7]
I couldn't start the game after updating to the mods to latest version
[crash-2022-10-30_17.10.08-client.txt](https://github.com/Enchanted-Games/vertical-slabs/files/9897098/crash-2022-10-30_17.10.08-client.txt)

**Comment by Enchanted-Games** [comment]
For now, use v1.5 while a fix is being worked on

**Comment by Enchanted-Games** [comment]
Fixed in v1.6
